title: "DSC 180A Methodology Assignment 4"
description: "Kaijie Zhang - UC San Diego Data Science Capstone"
theme: jekyll-theme-cayman

author: "Kaijie Zhang"
email: "kaijiez@ucsd.edu"

markdown: kramdown
highlighter: rouge
plugins:
  - jekyll-feed
  - jekyll-seo-tag
